#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

date_default_timezone_set("UTC");

$basePath = __DIR__;
$app = new Symfony\Component\Console\Application('Basecamp Tasks', '0.1');

$app->add(new Trea\Bct\Console\InitCommand);
$app->add(new Trea\Bct\Console\CommitCommand);

$app->run();
